INSERT INTO book (title) VALUES ('The Great Gatsby');
INSERT INTO book (title) VALUES ('1984');
INSERT INTO book (title) VALUES ('To Kill a Mockingbird');
INSERT INTO book (title) VALUES ('The Catcher in the Rye');
INSERT INTO book (title) VALUES ('Moby Dick');
INSERT INTO book (title) VALUES ('War and Peace');
INSERT INTO book (title) VALUES ('Hamlet');
INSERT INTO book (title) VALUES ('The Odyssey');
INSERT INTO book (title) VALUES ('Pride and Prejudice');
INSERT INTO book (title) VALUES ('The Hobbit');
INSERT INTO book (title) VALUES ('The Lord of the Rings');
INSERT INTO book (title) VALUES ('The Chronicles of Narnia');
INSERT INTO book (title) VALUES ('The Little Prince');
INSERT INTO book (title) VALUES ('The Alchemist');
INSERT INTO book (title) VALUES ('The Da Vinci Code');
INSERT INTO book (title) VALUES ('The Hunger Games');
INSERT INTO book (title) VALUES ('The Girl with the Dragon Tattoo');
INSERT INTO book (title) VALUES ('The Kite Runner');
INSERT INTO book (title) VALUES ('The Help');
INSERT INTO book (title) VALUES ('The Fault in Our Stars');
INSERT INTO book (title) VALUES ('The Twelve Chairs');

INSERT INTO author (name) VALUES ('F. Scott Fitzgerald');
INSERT INTO author (name) VALUES ('George Orwell');
INSERT INTO author (name) VALUES ('Harper Lee');
INSERT INTO author (name) VALUES ('J.D. Salinger');
INSERT INTO author (name) VALUES ('Herman Melville');
INSERT INTO author (name) VALUES ('Leo Tolstoy');
INSERT INTO author (name) VALUES ('William Shakespeare');
INSERT INTO author (name) VALUES ('Homer');
INSERT INTO author (name) VALUES ('Jane Austen');
INSERT INTO author (name) VALUES ('J.R.R. Tolkien');
INSERT INTO author (name) VALUES ('C.S. Lewis');
INSERT INTO author (name) VALUES ('Antoine de Saint-Exupéry');
INSERT INTO author (name) VALUES ('Paulo Coelho');
INSERT INTO author (name) VALUES ('Dan Brown');
INSERT INTO author (name) VALUES ('Suzanne Collins');
INSERT INTO author (name) VALUES ('Stieg Larsson');
INSERT INTO author (name) VALUES ('Khaled Hosseini');
INSERT INTO author (name) VALUES ('Kathryn Stockett');
INSERT INTO author (name) VALUES ('John Green');
INSERT INTO author (name) VALUES ('Ilya Ilf');
INSERT INTO author (name) VALUES ('Yevgeny Petrov');


INSERT INTO author_book (book_id, author_id) VALUES (1, 1);
INSERT INTO author_book (book_id, author_id) VALUES (2, 2);
INSERT INTO author_book (book_id, author_id) VALUES (3, 3);
INSERT INTO author_book (book_id, author_id) VALUES (4, 4);
INSERT INTO author_book (book_id, author_id) VALUES (5, 5);
INSERT INTO author_book (book_id, author_id) VALUES (6, 6);
INSERT INTO author_book (book_id, author_id) VALUES (7, 7);
INSERT INTO author_book (book_id, author_id) VALUES (8, 8);
INSERT INTO author_book (book_id, author_id) VALUES (9, 9);
INSERT INTO author_book (book_id, author_id) VALUES (10, 10);
INSERT INTO author_book (book_id, author_id) VALUES (11, 10);
INSERT INTO author_book (book_id, author_id) VALUES (12, 11);
INSERT INTO author_book (book_id, author_id) VALUES (13, 12);
INSERT INTO author_book (book_id, author_id) VALUES (14, 13);
INSERT INTO author_book (book_id, author_id) VALUES (15, 14);
INSERT INTO author_book (book_id, author_id) VALUES (16, 15);
INSERT INTO author_book (book_id, author_id) VALUES (17, 16);
INSERT INTO author_book (book_id, author_id) VALUES (18, 17);
INSERT INTO author_book (book_id, author_id) VALUES (19, 18);
INSERT INTO author_book (book_id, author_id) VALUES (20, 19);
INSERT INTO author_book (book_id, author_id) VALUES (21, 20);
INSERT INTO author_book (book_id, author_id) VALUES (21, 21);